[package]
name = "http-server"
version = "0.1.0"
authors = ["aruniljaiswal <aruniljaiswal27@gmail.com>"]
edition = "2024"

[dependencies]
dotenv = "0.14"
envy = "0.4"
env_logger = "0.7.1"
flate2 = "1.0"
lazy_static = "1.4"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"